import { Alert, Linking, ScrollView, Text, View } from "react-native";
import { API_BASE } from "../api";
import { Card, PrimaryButton, Screen, styles } from "../components";

const reports = [
  ["P101 Seal Failure RCA", "/api/reports/download/rca?asset_tag=P-101"],
  ["Q2 Compliance Evidence Package", "/api/reports/download/audit-package"],
  ["Executive Risk Summary", "/api/reports/download/executive-summary"],
  ["Preventive Maintenance Backlog", "/api/reports/download/maintenance-report"]
];

export function ReportsScreen() {
  async function openReport(path: string) {
    const url = `${API_BASE}${path}`;
    const supported = await Linking.canOpenURL(url);
    if (!supported) {
      Alert.alert("Cannot open report", url);
      return;
    }
    await Linking.openURL(url);
  }

  return (
    <ScrollView>
      <Screen title="Reports Center" subtitle="Open generated PDFs from the same backend report service.">
        <View style={{ gap: 12 }}>
          {reports.map(([title, path]) => (
            <Card key={title}>
              <Text style={styles.body}>{title}</Text>
              <Text style={styles.muted}>PDF generated by FastAPI backend</Text>
              <View style={{ marginTop: 12 }}>
                <PrimaryButton label="Open PDF" onPress={() => void openReport(path)} />
              </View>
            </Card>
          ))}
        </View>
      </Screen>
    </ScrollView>
  );
}
