export type ProviderName = 'omi' | 'qdrant' | 'lyzr' | 'local fallback' | 'unavailable';
export type Scope = { sub: string; tenant: string; plant: string; organization_id?: string; plant_id?: string; role: string };
export type Health = { provider: string; status: 'healthy' | 'degraded' | 'disabled' | 'unavailable' | 'misconfigured'; checked_at: string; last_success: string | null; detail: string; vector_count?: number; collection?: string; workflow?: string; agent?: string };
export type Evidence = { id: string; document_id: string; text: string; tenant: string; plant: string; organization_id?: string; plant_id?: string; permission_scope: string[]; filename: string; doc_type: string; section: string; page_number: number | null; timestamp: string | null; asset_tag: string[]; content_hash: string; ingestion_version: string; omi_conversation_id?: string; score?: number; source_id?: string; source_provider?: 'omi'; demonstration_data?: boolean; classification?: string; operational_authorization?: false; provenance?: Observation['provenance']; approval?: {actor:string;at:string;purpose:string} };
export type Observation = { id: string; source_id: string; conversation_id: string; provider: 'omi'; tenant: string; plant: string; organization_id?: string; plant_id?: string; imported_by: string; imported_at: string; timestamp: string | null; transcript: string; speakers: string[]; asset_tag: string[]; observation: string; defect: string[]; recommended_action: string[]; responsible_role: string | null; due_date: string | null; confidence: null; content_hash: string; demonstration_data?: boolean; classification?: string; operational_authorization?: false; proposed_review_actions?: string[]; extraction_method?: string; timestamp_source?: string|null; provenance: { conversation_id: string; segment_indexes: number[]; source_provider?: 'omi'; segments?: Array<{index:number;id?:string;start?:number;end?:number}> }; status: 'pending' | 'approved' | 'rejected'; indexing: 'not_indexed' | 'indexed' | 'failed'; reviewed_by?: string; reviewed_at?: string };
export type Claim = { kind: 'fact' | 'inference'; text: string; citations: string[]; quote?: string };
export type Step = { name: string; status: string; started_at?: string; ended_at?: string; provider: string; evidence_count?: number; claims_submitted?:number; evidence_assignments?:number };
export type Execution = { id: string; scope: Scope; question: string; status: 'running' | 'complete' | 'failed'; provider: ProviderName; started_at: string; ended_at?: string; provider_execution_id?: string; provider_session_id?: string; orchestration_mode?: string; evidence: Evidence[]; claims: Claim[]; steps: Step[]; human_review_required: boolean; review?: { actor: string; decision: 'reviewed' | 'rejected'; at: string }; error?: string; validation?: {raw_count:number;validated_count:number;rejected_count:number;method:string;contract_version?:string;contract_error?:string;decisions?:import('./validation').Decision[];trace?:{qdrant_passages:number;orchestrator_unique_passages:number;verifier_unique_passages:number;evidence_assignments:number;claims_submitted:number;locally_rejected:number;verifier_entries:number;claims_released:number}}; capability_hash?: string; capability_expires?: number };
export interface HealthCheckProvider { health(): Promise<Health> }
export interface ConversationProvider extends HealthCheckProvider { list(offset?: number): Promise<unknown[]>; get(id: string): Promise<unknown> }
export interface EmbeddingProvider { embed(texts: string[], purpose?: 'passage'|'query'): Promise<number[][]>; dimension: number }
export interface VectorStoreProvider extends HealthCheckProvider { upsert(evidence: Evidence[]): Promise<void>; search(question: string, scope: Scope, asset?: string): Promise<Evidence[]>; deleteDocument(id: string, scope: Scope): Promise<void> }
export interface AgentOrchestratorProvider extends HealthCheckProvider { execute(input: Record<string, unknown>): Promise<{ output: unknown; execution_id?: string; session_id?: string }> }
export interface AuditProvider { record(scope: Scope, action: string, target: string, detail?: string): Promise<void> }
